wecenter:
  restart: always
  build: .
  links:
    - db
  ports:
    - "8080:80"
  volumes:
    - /srv/wecenter/uploads:/app/uploads
    - /srv/wecenter/system_bak:/app/system_bak
    - /srv/wecenter/config:/var/www/html/system/config
db:
  restart: always
  image: mysql
  ports:
    - "3306:3306"
  environment:
    MYSQL_ROOT_PASSWORD: 123456
    MYSQL_USER: dev
    MYSQL_PASSWORD: 123456
    MYSQL_DATABASE: myapp
  volumes:
    - /srv/wecenter/db/data:/var/lib/mysql
phpmyadmin:
  restart: always
  image: phpmyadmin/phpmyadmin
  links:
    - db
  environment:
    PMA_HOST: db
    PMA_PORT: 3306
    PMA_USER: dev
    PMA_PASSWORD: 123456
  ports:
    - 8081:80
  volumes:
    - /srv/wecenter/phpmyadmin/sessions:/sessions
